### ISSUE TITLE
Problema al resetear con el botón

### ISSUE THREAD

**Issue by DiegoPinillaU** [vbustos01/collarVacas#1]
Luego de reiniciar la ESP usando el botón de reset, en la consola se observa el siguiente mensaje de error.
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "lora.py", line 150, in <module>
  File "lora.py", line 38, in __init__
  File "drivers/controller.py", line 63, in add_transceiver
  File "drivers/sx127x.py", line 98, in init
Exception: Invalid version.
```

**Comment by vbustos01** [comment]
that's crazy

**Comment by SANCHEZJOSE** [comment]
Ok! gracias por avisar

**Comment by DiegoPinillaU** [comment]
Finalmente @SANCHEZJOSE soluciona agregando reintentos en el inicio del dispositivo LoRa.
